version: "3.7"

networks:
  caddy:
    external: true

services:
  backend:
    build: backend
    networks:
      - caddy
    env_file: stripe.env
    labels:
      caddy: semudando.com.br
      caddy.handle_path: /api/*
      caddy.handle_path.0_reverse_proxy: "{{upstreams 9090}}"
  frontend:
    build: frontend
    networks:
      - caddy
    labels:
      caddy: semudando.com.br
      caddy.reverse_proxy: "{{upstreams 80}}"
