version: "3.8"

services:
  web:
    image: danjellz/http-server
    expose:
      - 8080
    volumes:
      - ./web:/public
    labels:
      caddy: beta.semudando.com.br
      caddy.reverse_proxy: "{{upstreams 8080}}"
    networks:
      - caddy

networks:
  caddy:
    external: true
