version: "3.8"

services:
  web:
    image: semudando/web:1.0.0
    labels:
      caddy: semudando.com.br
      caddy.reverse_proxy: "{{upstreams 8080}}"
    networks:
      - caddy

networks:
  caddy:
    external: true
